Feature. Manual combobox item select.
nebosite/mvvm_on_react pull request #5
Opened 2019-12-13 22:00 UTC by velidan

- added a manual combobox select via appModel chooseStrawberry method
- implemented tests
- created a flawors data object to easily re-use the flavors by a pointer. String hardcoding is fragile

2019-12-13 23:50 UTC, nebosite requested changes

2019-12-13 23:50 UTC, nebosite commented on src/models/__tests__/appmodel.test.ts
> +		expect(appModel.selectedFlavor).toBe(flaworsData.strawberry);
In the name of keeping it simple a literal "Strawberry" is sufficient here.

2019-12-13 23:50 UTC, nebosite commented on src/models/appmodel.ts
> +export const flaworsData = {
Would rather leave out this structure in the name of keeping it simple

2019-12-16 19:41 UTC, velidan commented
Removed flavor registry, rollback to string values

2019-12-17 15:20 UTC, merged